import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/header";
import Providers from "@/providers/all";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ZeroK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          <ToastContainer theme="dark" />
        </body>
      </html>
    </Providers>
  );
}
